### ISSUE TITLE
发送给群内特定的人

### ISSUE THREAD

**Issue by marvin9551** [anjia0532/weixin-qiye-alert#1]
请问作者，怎样设置能够实现将不同的消息推送给群内不同的人

**Comment by anjia0532** [comment]
建议通过配置文件进行扩展

https://raw.githubusercontent.com/anjia0532/weixin-qiye-alert/master/src/main/resources/cp.properties

如果消息有明显特征，比如，不同消息前几位不同，或者模块，或者包等不同，可以将不同的部分设置成微信企业号的标签，然后在标签内加人。进行区分发送

如果能将消息按照功能或者模块进行区分的话，原理同上。

https://github.com/anjia0532/weixin-qiye-alert/blob/master/src/main/java/com/anjia/WeiXinAlert.java#L150

微信接口只能用tagId，我是通过获取所有的标签，然后进行遍历比对，有符合的就推到相应标签。如果对性能要求比较高，可以用缓存框架，或者静态map缓存，key是tagName，value是tagId，初始化时从微信获取所有的，放入缓存，后期直接map.getKey，注意缓存数据失效（手动添加新标签）
